//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualizationListViewControl.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualizationListViewControl.Localization.LocalizationDictionary", typeof(LocalizationDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string AddFilter {
            get {
                return ResourceManager.GetString("AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add argument to expression.
        /// </summary>
        public static string AddOperandToExpression {
            get {
                return ResourceManager.GetString("AddOperandToExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bracketed expression.
        /// </summary>
        public static string AddOperator {
            get {
                return ResourceManager.GetString("AddOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending sort.
        /// </summary>
        public static string AscendingSort {
            get {
                return ResourceManager.GetString("AscendingSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear expression.
        /// </summary>
        public static string ClearExpression {
            get {
                return ResourceManager.GetString("ClearExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Column not supported sorting].
        /// </summary>
        public static string ColumnWithoutSorting {
            get {
                return ResourceManager.GetString("ColumnWithoutSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string CountTitle {
            get {
                return ResourceManager.GetString("CountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose filter and expression argument for adding.
        /// </summary>
        public static string DefaultExpressionQueryText {
            get {
                return ResourceManager.GetString("DefaultExpressionQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose expression.
        /// </summary>
        public static string DefaultExpressionValueText {
            get {
                return ResourceManager.GetString("DefaultExpressionValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not supported filter by value.
        /// </summary>
        public static string DefaultFilterRowToolTip {
            get {
                return ResourceManager.GetString("DefaultFilterRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending sort.
        /// </summary>
        public static string DescendingSort {
            get {
                return ResourceManager.GetString("DescendingSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string EditQueriesButtonText {
            get {
                return ResourceManager.GetString("EditQueriesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression editor.
        /// </summary>
        public static string EditQueriesButtonToolTip {
            get {
                return ResourceManager.GetString("EditQueriesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUAL.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions arguments:.
        /// </summary>
        public static string ExpressionArgumentsTitle {
            get {
                return ResourceManager.GetString("ExpressionArgumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression query:.
        /// </summary>
        public static string ExpressionQueryTitle {
            get {
                return ResourceManager.GetString("ExpressionQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push for change filter.
        /// </summary>
        public static string FilterComboBoxToolTip {
            get {
                return ResourceManager.GetString("FilterComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter constructor.
        /// </summary>
        public static string FilterConfiguratorTitle {
            get {
                return ResourceManager.GetString("FilterConfiguratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters:.
        /// </summary>
        public static string FiltersListTitle {
            get {
                return ResourceManager.GetString("FiltersListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREATER.
        /// </summary>
        public static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREATER OR EQUAL.
        /// </summary>
        public static string GreaterOrEqual {
            get {
                return ResourceManager.GetString("GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESS.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESS OR EQUAL.
        /// </summary>
        public static string LessOrEqual {
            get {
                return ResourceManager.GetString("LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT EQUAL.
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Push for change sorting].
        /// </summary>
        public static string PushForChangeSorting {
            get {
                return ResourceManager.GetString("PushForChangeSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove argument from expression.
        /// </summary>
        public static string RemoveOperandFromExpression {
            get {
                return ResourceManager.GetString("RemoveOperandFromExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters list:.
        /// </summary>
        public static string SavedFiltersListTitle {
            get {
                return ResourceManager.GetString("SavedFiltersListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START WITH.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on field.
        /// </summary>
        public static string ValidationErrorText {
            get {
                return ResourceManager.GetString("ValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (without filter).
        /// </summary>
        public static string WithoutFilter {
            get {
                return ResourceManager.GetString("WithoutFilter", resourceCulture);
            }
        }
    }
}
